config/routes.rb
Rails.application.routes.draw do

  get 'books/new'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "homes#top"
  get "homes/about" => "homes#about"

  resources :users, only: [:new, :create, :index, :show, :edit, :update]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body,
    presence: true,
    length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name,
    presence: true,
    length: {minimum: 2, maximum: 20},
    uniqueness:true

  validates :introduction,
    length: {maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name, :email])
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :ensure_current_user,{only: [:edit, :update]}
  def ensure_current_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end


  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:success] = "You have created book successfully"
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top

  end

  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_current_user,{only:[:edit, :update]}
    def ensure_current_user
      @user = User.find(params[:id])
      if @user.id != current_user.id
        redirect_to user_path(current_user.id)
      end
    end

  def new
    @book = Book.new
  end

  def create
   @book = Book.new(book_params)
    # booksのuser_idカラムは現在ログイン中のIDで保存する
   @book.user_id = current_user.id
   @book.save
   redirect_to book_path(@book.id)
   flash[:success] = "You have created book successfully"
  end

  def index
    @users = User.all
    # index内（ユーザー一覧）に投稿を置く場合、newが必要
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    # @userに紐付いたbooksのみを表示
    @books = @user.books
    # show内（ユーザ詳細）に投稿を置く場合、newが必要
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:success]= "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_books.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>
    <div class="form-group">
      <label class="inputTitle">Title</label>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <label class="inputOpinion">Opinion</label>
      <%= f.text_area :body, row: "5", class: "form-control"%>
    </div>

    <%= f.submit "Create Book", class: "btn btn-success"%>
  <% end %>

app/views/books/_error.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>erros prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/books/edit.html.erb
<div class= "container mt-3 pb-5">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model: @book, local: true do |f| %>
        <div class="form-group">
          <label for="inputTitle">Title</label>
          <%= f.text_field :title, autofocus: true, id: "inputTitle", class: "form-control" %>
        </div>

        <div class="form-group">
          <label for="inputopinion">Opinion</label>
          <%= f.text_area :body, class: "form-control" %>
        </div>
          <%= f.submit "Update Book", class:"btn btn-success"%>
            <%if @book.user == current_user %>
              <div class="text-primary">
                <%= link_to "Show", book_path(@book)%>
                  |
                <%= link_to "Back", books_path %>
            <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3">

      <span class="text-danger"><strong><%= render "books/error" %></strong></span>

      <%= render "users/info", user: @user %>
      <%= render "books/books", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Books</h1>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size:"50x50" %>
              <% end %>
            </td>

            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>

            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user:@user %>
      <%= render "books/books", book:@book_new %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h1>Book detail</h1>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user,:profile_image, :fill, 100, 100, format:"jpeg", fallback: "no_image.jpg", size:"100x100" %><br />
                  <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                  <%= link_to "Destroy", book_path(@book), method: :delete, class: "btn btn-danger", data: {confirm: "本当に削除しますか？"} %>
                <% end %>
              </td>
            <tr>
          </tbody>
        </div>
      </div>
    </div>
  </div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row col-12 p-3">
    <div class="mx-auto">
    <h1>Welcome to<i class="fas fa-book"></i><strong>Bookers!</strong></h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container" >
  <div class="row col-12 p-3">
    <div class="mx-auto">
      <h1>welcome to<i class="fas fa-book"></i><strong>Bookers!!</strong></h1>
      <p>In<i class="fas fa-book"></i><strong>Bookers</strong>
      <p>you can share and exchange your opinions, inpressions, and emotions</p>
      <p>about various books!</p>
      <div class="col-11">
        <%= link_to "Log in", new_user_session_path, class: "text-light btn btn-info btn-block "%>
        <%= link_to "Sign up", new_user_registration_path, class: "text-light btn btn-success btn-block" %>
      </div>
    </div>
  <div>
</div>

app/views/layouts/_message.html.erb
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class:"#{key}") %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class = "navbar navbar-expand-lg navbar-dark bg-dark">
        <div class = "container">
          <a class ="navbar-brand" href = "/"><span>Bookers</span></a>
          <button class = "navbar-toggler" type = "button" data-toggle = "collapse" data-target = "#navbarNavDropdown" aria-controls = "navbarNavDropdown" aria-expanded = "false" aria-label = "Toggle navigation">
            <span class = "navbar-toggler-icon" ></span>
          </button>
          <div class = "collapse navbar-collapse" id = "navbarNavDropdown">
            <ul class = "navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class = "nav-item">
                <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
              </li>
              <% else %>
              <li class = "nav-item">
                <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "About", homes_about_path, class: 'fas fa-link nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "Sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
              </li>
              <li class = "nav-item">
                <%= link_to "Log in", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <span class="text-success"><%= render 'layouts/message' %></span>

    <%= yield %>
  </body>
</html>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:<br />
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

app/views/users/_info.html.erb
<!--プロフィール-->
<!--ここでの修正を最小限にするため、呼び出し元でローカル変数を定義している-->
<h2 class="mt-3">User info</h2>
  <table class="table">
    <tr>
      <td><%= attachment_image_tag user,:profile_image, :fill, 60, 60, format:"jpeg",fallback:"no_image.jpg",size:"60x60" %></td>
      <td></td>
    </tr>
    <tr>
      <th>name</th>
      <th><%= user.name %>
    </tr>
    <tr>
      <th>introduction</th>
      <td><%= user.introduction %></td>
    </tr>
  </table>

  <%= link_to edit_user_path(current_user.id),class:"btn btn-block btn-outline-secondary p-0 mt-3" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>

app/views/users/edit.html.erb
<div class="container pt-3 pb-5">
  <div class="row">
    <div class="col-md-5 mx-auto">
      <h2>User info</h2>
      <span class="text-danger"><strong><%= render "users/errors"%></strong></span>
        <%= form_with model:@user, local: true do |f| %>
        <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control" %>
        </div>

        <div>
          <label from="inputImage">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "ファイルを選択" %>
        </div>

        <div class="form-group py-3">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, row: "5", class:"form-control", placeholder:"自己紹介" %>
        </div>
          <%= f.submit "Update User", class:"text-light btn-secondary"%>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>
      <%= render "books/books", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <% @users.each do |user| %>
        <tbody>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg",size:'60x60' %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              <%= link_to "Show",user_path(user.id) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class= "text-success"><%= flash[:success] %></div>
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render "users/info", user: @user %>

      <%= render "books/books", book: @book %>
    </div>

    <div class="col-md-8 offset-md-1 mt-3">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>

        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
              <% end %>
            </td>

            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title %>
              <% end %>
            </td>

            <td>
              <%= book.body %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>